from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import func

db = SQLAlchemy()

# ---------- Basic ----------

class SysRegion(db.Model):
    __tablename__ = 'sys_region'
    region_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    parent_id = db.Column(db.BigInteger)
    region_name = db.Column(db.String(64), nullable=False)
    region_code = db.Column(db.String(20), nullable=False)
    level = db.Column(db.SmallInteger, nullable=False, default=1)
    sort_order = db.Column(db.Integer, default=0)
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class SysDict(db.Model):
    __tablename__ = 'sys_dict'
    dict_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    dict_type = db.Column(db.String(64), nullable=False)
    dict_label = db.Column(db.String(128), nullable=False)
    dict_value = db.Column(db.String(128), nullable=False)
    sort_order = db.Column(db.Integer, default=0)
    remark = db.Column(db.String(256))
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class UsrUser(db.Model):
    __tablename__ = 'usr_user'
    user_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    phone = db.Column(db.String(20), nullable=False, unique=True)
    password_hash = db.Column(db.String(256))
    nickname = db.Column(db.String(64))
    avatar_url = db.Column(db.String(512))
    gender = db.Column(db.SmallInteger, default=0)
    openid_wechat = db.Column(db.String(128), unique=True)
    unionid_wechat = db.Column(db.String(128))
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    last_login_at = db.Column(db.DateTime(3))
    last_login_ip = db.Column(db.String(45))
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class UsrElderly(db.Model):
    __tablename__ = 'usr_elderly'
    elderly_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    user_id = db.Column(db.BigInteger, nullable=False, unique=True)
    name = db.Column(db.String(32), nullable=False)
    id_card = db.Column(db.String(18))
    gender = db.Column(db.SmallInteger, nullable=False)
    birth_date = db.Column(db.Date)
    age = db.Column(db.SmallInteger)
    phone = db.Column(db.String(20))
    address = db.Column(db.String(256))
    region_id = db.Column(db.BigInteger)
    longitude = db.Column(db.Numeric(10, 6))
    latitude = db.Column(db.Numeric(10, 6))
    living_status = db.Column(db.SmallInteger, nullable=False, default=1)
    health_level = db.Column(db.SmallInteger, nullable=False, default=1)
    emergency_contact_name = db.Column(db.String(32))
    emergency_contact_phone = db.Column(db.String(20))
    blood_type = db.Column(db.String(2))
    allergies = db.Column(db.String(512))
    medical_history = db.Column(db.Text)
    privacy_mode = db.Column(db.SmallInteger, nullable=False, default=0)
    sos_enabled = db.Column(db.SmallInteger, nullable=False, default=1)
    profile_photo_url = db.Column(db.String(512))
    remark = db.Column(db.String(512))
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class UsrFamilyBind(db.Model):
    __tablename__ = 'usr_family_bind'
    bind_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    family_user_id = db.Column(db.BigInteger, nullable=False)
    relation_type = db.Column(db.String(16), nullable=False)
    is_primary = db.Column(db.SmallInteger, nullable=False, default=0)
    alert_enabled = db.Column(db.SmallInteger, nullable=False, default=1)
    service_perm = db.Column(db.SmallInteger, nullable=False, default=1)
    health_perm = db.Column(db.SmallInteger, nullable=False, default=1)
    video_perm = db.Column(db.SmallInteger, nullable=False, default=1)
    bind_time = db.Column(db.DateTime(3), server_default=func.now(3))
    verify_status = db.Column(db.SmallInteger, nullable=False, default=0)
    verified_by = db.Column(db.BigInteger)
    verified_at = db.Column(db.DateTime(3))
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class UsrServiceWorker(db.Model):
    __tablename__ = 'usr_service_worker'
    worker_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    user_id = db.Column(db.BigInteger, nullable=False, unique=True)
    name = db.Column(db.String(32), nullable=False)
    id_card = db.Column(db.String(18))
    gender = db.Column(db.SmallInteger, nullable=False)
    phone = db.Column(db.String(20), nullable=False)
    region_id = db.Column(db.BigInteger)
    worker_type = db.Column(db.SmallInteger, nullable=False, default=1)
    service_tags = db.Column(db.String(256))
    id_card_front_url = db.Column(db.String(512))
    id_card_back_url = db.Column(db.String(512))
    cert_health_url = db.Column(db.String(512))
    cert_no = db.Column(db.String(64))
    bank_account = db.Column(db.String(32))
    bank_name = db.Column(db.String(64))
    total_orders = db.Column(db.Integer, nullable=False, default=0)
    completed_orders = db.Column(db.Integer, nullable=False, default=0)
    avg_rating = db.Column(db.Numeric(2, 1))
    credit_score = db.Column(db.Integer, default=100)
    status = db.Column(db.SmallInteger, nullable=False, default=0)
    applied_formal_at = db.Column(db.DateTime(3))
    reviewed_by = db.Column(db.BigInteger)
    reviewed_at = db.Column(db.DateTime(3))
    review_remark = db.Column(db.String(256))
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class UsrStreetAdmin(db.Model):
    __tablename__ = 'usr_street_admin'
    admin_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    user_id = db.Column(db.BigInteger, nullable=False, unique=True)
    name = db.Column(db.String(32), nullable=False)
    phone = db.Column(db.String(20), nullable=False)
    region_id = db.Column(db.BigInteger, nullable=False)
    role_type = db.Column(db.SmallInteger, nullable=False, default=1)
    dept_name = db.Column(db.String(64))
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class UsrPartnerOrg(db.Model):
    __tablename__ = 'usr_partner_org'
    org_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    org_name = db.Column(db.String(128), nullable=False)
    org_type = db.Column(db.SmallInteger, nullable=False)
    contact_person = db.Column(db.String(32))
    contact_phone = db.Column(db.String(20))
    license_no = db.Column(db.String(64))
    address = db.Column(db.String(256))
    region_id = db.Column(db.BigInteger)
    api_key = db.Column(db.String(128))
    webhook_url = db.Column(db.String(512))
    contract_start = db.Column(db.Date)
    contract_end = db.Column(db.Date)
    status = db.Column(db.SmallInteger, nullable=False, default=0)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class UsrDevice(db.Model):
    __tablename__ = 'usr_device'
    device_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    device_sn = db.Column(db.String(64), nullable=False, unique=True)
    device_type = db.Column(db.SmallInteger, nullable=False)
    device_model = db.Column(db.String(64))
    manufacturer = db.Column(db.String(64))
    firmware_ver = db.Column(db.String(32))
    elderly_id = db.Column(db.BigInteger, nullable=False)
    install_location = db.Column(db.String(64))
    longitude = db.Column(db.Numeric(10, 6))
    latitude = db.Column(db.Numeric(10, 6))
    is_online = db.Column(db.SmallInteger, nullable=False, default=0)
    last_heartbeat = db.Column(db.DateTime(3))
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    installed_at = db.Column(db.DateTime(3))
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class SafAlert(db.Model):
    __tablename__ = 'saf_alert'
    alert_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    alert_no = db.Column(db.String(32), nullable=False, unique=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    device_id = db.Column(db.BigInteger)
    alert_type = db.Column(db.SmallInteger, nullable=False)
    alert_level = db.Column(db.SmallInteger, nullable=False)
    confidence = db.Column(db.Numeric(5, 2))
    alert_time = db.Column(db.DateTime(3), nullable=False)
    location_desc = db.Column(db.String(128))
    snapshot_url = db.Column(db.String(512))
    video_clip_url = db.Column(db.String(512))
    notify_family_at = db.Column(db.DateTime(3))
    family_responded_at = db.Column(db.DateTime(3))
    family_response = db.Column(db.SmallInteger)
    escalate_street_at = db.Column(db.DateTime(3))
    street_admin_id = db.Column(db.BigInteger)
    street_responded_at = db.Column(db.DateTime(3))
    street_action = db.Column(db.SmallInteger)
    escalate_120_at = db.Column(db.DateTime(3))
    call_120_result = db.Column(db.SmallInteger)
    cancel_reason = db.Column(db.String(128))
    cancelled_by = db.Column(db.BigInteger)
    cancelled_at = db.Column(db.DateTime(3))
    alert_status = db.Column(db.SmallInteger, nullable=False, default=0)
    resolved_at = db.Column(db.DateTime(3))
    resolve_remark = db.Column(db.String(512))
    response_seconds = db.Column(db.Integer)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class SafAlertNotify(db.Model):
    __tablename__ = 'saf_alert_notify'
    notify_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    alert_id = db.Column(db.BigInteger, nullable=False)
    channel = db.Column(db.SmallInteger, nullable=False)
    target_id = db.Column(db.BigInteger, nullable=False)
    target_type = db.Column(db.SmallInteger, nullable=False)
    send_status = db.Column(db.SmallInteger, nullable=False, default=0)
    send_at = db.Column(db.DateTime(3))
    read_at = db.Column(db.DateTime(3))
    error_msg = db.Column(db.String(256))
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class SafAiEvent(db.Model):
    __tablename__ = 'saf_ai_event'
    event_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    device_id = db.Column(db.BigInteger, nullable=False)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    event_type = db.Column(db.String(32), nullable=False)
    confidence = db.Column(db.Numeric(5, 2), nullable=False)
    event_time = db.Column(db.DateTime(3), nullable=False)
    snapshot_url = db.Column(db.String(512))
    model_version = db.Column(db.String(32))
    raw_data_ref = db.Column(db.String(256))
    processed = db.Column(db.SmallInteger, nullable=False, default=0)
    related_alert_id = db.Column(db.BigInteger)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class SvcCategory(db.Model):
    __tablename__ = 'svc_category'
    category_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    parent_id = db.Column(db.BigInteger)
    category_name = db.Column(db.String(64), nullable=False)
    category_code = db.Column(db.String(32), nullable=False, unique=True)
    icon_url = db.Column(db.String(512))
    description = db.Column(db.String(256))
    sort_order = db.Column(db.Integer, default=0)
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class SvcProduct(db.Model):
    __tablename__ = 'svc_product'
    product_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    category_id = db.Column(db.BigInteger, nullable=False)
    product_name = db.Column(db.String(128), nullable=False)
    product_desc = db.Column(db.Text)
    cover_image = db.Column(db.String(512))
    price_standard = db.Column(db.Numeric(10, 2), nullable=False, default=0)
    price_unit = db.Column(db.String(16), nullable=False, default='\u6b21')
    duration_min = db.Column(db.Integer)
    service_scope = db.Column(db.String(256))
    booking_rules = db.Column(db.JSON)
    org_id = db.Column(db.BigInteger)
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class SvcOrder(db.Model):
    __tablename__ = 'svc_order'
    order_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    order_no = db.Column(db.String(32), nullable=False, unique=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    order_from = db.Column(db.SmallInteger, nullable=False, default=1)
    buyer_user_id = db.Column(db.BigInteger, nullable=False)
    product_id = db.Column(db.BigInteger, nullable=False)
    service_date = db.Column(db.Date, nullable=False)
    time_slot_start = db.Column(db.Time)
    time_slot_end = db.Column(db.Time)
    service_address = db.Column(db.String(256))
    contact_name = db.Column(db.String(32))
    contact_phone = db.Column(db.String(20))
    original_price = db.Column(db.Numeric(10, 2), nullable=False, default=0)
    discount_amount = db.Column(db.Numeric(10, 2), nullable=False, default=0)
    final_price = db.Column(db.Numeric(10, 2), nullable=False, default=0)
    pay_method = db.Column(db.SmallInteger)
    pay_status = db.Column(db.SmallInteger, nullable=False, default=0)
    paid_at = db.Column(db.DateTime(3))
    order_status = db.Column(db.SmallInteger, nullable=False, default=0)
    worker_id = db.Column(db.BigInteger)
    accepted_at = db.Column(db.DateTime(3))
    checkin_at = db.Column(db.DateTime(3))
    checkin_lat = db.Column(db.Numeric(10, 6))
    checkin_lng = db.Column(db.Numeric(10, 6))
    checkout_at = db.Column(db.DateTime(3))
    checkout_lat = db.Column(db.Numeric(10, 6))
    checkout_lng = db.Column(db.Numeric(10, 6))
    finish_photos = db.Column(db.JSON)
    finish_remark = db.Column(db.String(512))
    completed_at = db.Column(db.DateTime(3))
    rating = db.Column(db.SmallInteger)
    review_content = db.Column(db.String(512))
    reviewed_at = db.Column(db.DateTime(3))
    cancel_reason = db.Column(db.String(256))
    cancelled_by = db.Column(db.BigInteger)
    cancelled_at = db.Column(db.DateTime(3))
    refund_amount = db.Column(db.Numeric(10, 2))
    refunded_at = db.Column(db.DateTime(3))
    remark = db.Column(db.String(512))
    ext_info = db.Column(db.JSON)
    version = db.Column(db.Integer, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class SvcOrderLog(db.Model):
    __tablename__ = 'svc_order_log'
    log_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    order_id = db.Column(db.BigInteger, nullable=False)
    action = db.Column(db.String(32), nullable=False)
    from_status = db.Column(db.SmallInteger)
    to_status = db.Column(db.SmallInteger)
    operator_id = db.Column(db.BigInteger)
    operator_type = db.Column(db.SmallInteger)
    remark = db.Column(db.String(512))
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class SvcWorkerWallet(db.Model):
    __tablename__ = 'svc_worker_wallet'
    wallet_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    worker_id = db.Column(db.BigInteger, nullable=False, unique=True)
    balance = db.Column(db.Numeric(10, 2), nullable=False, default=0)
    frozen_amount = db.Column(db.Numeric(10, 2), nullable=False, default=0)
    total_income = db.Column(db.Numeric(10, 2), nullable=False, default=0)
    total_withdrawn = db.Column(db.Numeric(10, 2), nullable=False, default=0)
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class SvcSettlement(db.Model):
    __tablename__ = 'svc_settlement'
    settle_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    order_id = db.Column(db.BigInteger, nullable=False)
    worker_id = db.Column(db.BigInteger, nullable=False)
    type = db.Column(db.SmallInteger, nullable=False)
    amount = db.Column(db.Numeric(10, 2), nullable=False)
    balance_before = db.Column(db.Numeric(10, 2), nullable=False)
    balance_after = db.Column(db.Numeric(10, 2), nullable=False)
    title = db.Column(db.String(128), nullable=False)
    ref_no = db.Column(db.String(64))
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class HltMedicationPlan(db.Model):
    __tablename__ = 'hlt_medication_plan'
    plan_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    drug_name = db.Column(db.String(64), nullable=False)
    drug_generic = db.Column(db.String(64))
    dosage = db.Column(db.String(32), nullable=False)
    frequency = db.Column(db.SmallInteger, nullable=False)
    take_times = db.Column(db.JSON, nullable=False)
    route = db.Column(db.String(16), default='\u53e3\u670d')
    start_date = db.Column(db.Date, nullable=False)
    end_date = db.Column(db.Date)
    prescriber = db.Column(db.String(64))
    source = db.Column(db.SmallInteger, default=1)
    stock_count = db.Column(db.Integer)
    reminder_advance_min = db.Column(db.Integer, default=15)
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_by = db.Column(db.BigInteger)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class HltMedicationReminder(db.Model):
    __tablename__ = 'hlt_medication_reminder'
    reminder_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    plan_id = db.Column(db.BigInteger, nullable=False)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    scheduled_time = db.Column(db.DateTime(3), nullable=False)
    sent_at = db.Column(db.DateTime(3))
    send_channel = db.Column(db.SmallInteger)
    taken_at = db.Column(db.DateTime(3))
    taken_status = db.Column(db.SmallInteger, default=0)
    skip_reason = db.Column(db.String(128))
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class HltMetricDef(db.Model):
    __tablename__ = 'hlt_metric_def'
    metric_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    metric_code = db.Column(db.String(32), nullable=False, unique=True)
    metric_name = db.Column(db.String(64), nullable=False)
    unit = db.Column(db.String(16))
    category = db.Column(db.SmallInteger, nullable=False)
    normal_min = db.Column(db.Numeric(10, 2))
    normal_max = db.Column(db.Numeric(10, 2))
    warn_min = db.Column(db.Numeric(10, 2))
    warn_max = db.Column(db.Numeric(10, 2))
    danger_min = db.Column(db.Numeric(10, 2))
    danger_max = db.Column(db.Numeric(10, 2))
    color_rule = db.Column(db.JSON)
    sort_order = db.Column(db.Integer, default=0)
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class HltHealthData(db.Model):
    __tablename__ = 'hlt_health_data'
    data_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    device_id = db.Column(db.BigInteger)
    metric_code = db.Column(db.String(32), nullable=False)
    value_num = db.Column(db.Numeric(10, 2))
    value_str = db.Column(db.String(64))
    value_extra = db.Column(db.JSON)
    measure_time = db.Column(db.DateTime(3), nullable=False)
    upload_time = db.Column(db.DateTime(3), server_default=func.now(3))
    data_source = db.Column(db.SmallInteger, nullable=False, default=1)
    is_abnormal = db.Column(db.SmallInteger, default=0)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class HltDoctorBinding(db.Model):
    __tablename__ = 'hlt_doctor_binding'
    binding_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    doctor_name = db.Column(db.String(32), nullable=False)
    doctor_phone = db.Column(db.String(20))
    hospital_name = db.Column(db.String(128))
    department = db.Column(db.String(64))
    org_id = db.Column(db.BigInteger)
    sign_date = db.Column(db.Date, nullable=False)
    expire_date = db.Column(db.Date)
    status = db.Column(db.SmallInteger, nullable=False, default=1)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class HltHealthAlert(db.Model):
    __tablename__ = 'hlt_health_alert'
    alert_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    metric_code = db.Column(db.String(32), nullable=False)
    alert_level = db.Column(db.SmallInteger, nullable=False)
    alert_value = db.Column(db.Numeric(10, 2), nullable=False)
    normal_range = db.Column(db.String(64))
    continuous_days = db.Column(db.Integer, nullable=False, default=1)
    alert_time = db.Column(db.DateTime(3), nullable=False)
    notify_family = db.Column(db.SmallInteger, nullable=False, default=0)
    notify_doctor = db.Column(db.SmallInteger, nullable=False, default=0)
    resolved = db.Column(db.SmallInteger, nullable=False, default=0)
    resolved_at = db.Column(db.DateTime(3))
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class CmpChatSession(db.Model):
    __tablename__ = 'cmp_chat_session'
    session_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    initiator_type = db.Column(db.SmallInteger, nullable=False, default=1)
    started_at = db.Column(db.DateTime(3), server_default=func.now(3))
    ended_at = db.Column(db.DateTime(3))
    message_count = db.Column(db.Integer, nullable=False, default=0)
    duration_sec = db.Column(db.Integer)
    sentiment_avg = db.Column(db.Numeric(3, 2))
    risk_flag = db.Column(db.SmallInteger, nullable=False, default=0)
    summary = db.Column(db.Text)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class CmpChatMessage(db.Model):
    __tablename__ = 'cmp_chat_message'
    message_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    session_id = db.Column(db.BigInteger, nullable=False)
    role = db.Column(db.SmallInteger, nullable=False)
    content_type = db.Column(db.SmallInteger, nullable=False, default=1)
    content_text = db.Column(db.Text, nullable=False)
    voice_url = db.Column(db.String(512))
    sentiment = db.Column(db.Numeric(3, 2))
    emotion_labels = db.Column(db.JSON)
    model_version = db.Column(db.String(32))
    token_count = db.Column(db.Integer)
    latency_ms = db.Column(db.Integer)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class CmpVideoVisit(db.Model):
    __tablename__ = 'cmp_video_visit'
    visit_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    elderly_id = db.Column(db.BigInteger, nullable=False)
    caller_user_id = db.Column(db.BigInteger, nullable=False)
    call_type = db.Column(db.SmallInteger, nullable=False, default=1)
    started_at = db.Column(db.DateTime(3), nullable=False)
    ended_at = db.Column(db.DateTime(3))
    duration_sec = db.Column(db.Integer)
    call_status = db.Column(db.SmallInteger, nullable=False, default=0)
    hangup_side = db.Column(db.SmallInteger)
    quality_score = db.Column(db.SmallInteger)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class CmpCompanionPref(db.Model):
    __tablename__ = 'cmp_companion_pref'
    pref_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    elderly_id = db.Column(db.BigInteger, nullable=False, unique=True)
    nickname_ai = db.Column(db.String(32), default='\u5c0f\u94f6')
    voice_type = db.Column(db.String(32), default='female_gentle')
    topics_interest = db.Column(db.JSON)
    chat_frequency = db.Column(db.SmallInteger, nullable=False, default=1)
    active_hours_start = db.Column(db.Time)
    active_hours_end = db.Column(db.Time)
    avoid_topics = db.Column(db.JSON)
    personality = db.Column(db.String(32), default='warm')
    memory_context = db.Column(db.Text)
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class CmmRegionConfig(db.Model):
    __tablename__ = 'cmm_region_config'
    config_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    region_id = db.Column(db.BigInteger, nullable=False)
    config_key = db.Column(db.String(64), nullable=False)
    config_value = db.Column(db.Text, nullable=False)
    description = db.Column(db.String(256))
    updated_by = db.Column(db.BigInteger)
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class CmmTicket(db.Model):
    __tablename__ = 'cmm_ticket'
    ticket_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    ticket_no = db.Column(db.String(32), nullable=False, unique=True)
    region_id = db.Column(db.BigInteger, nullable=False)
    ticket_type = db.Column(db.SmallInteger, nullable=False)
    priority = db.Column(db.SmallInteger, nullable=False, default=2)
    title = db.Column(db.String(128), nullable=False)
    description = db.Column(db.Text)
    elderly_id = db.Column(db.BigInteger)
    reporter_id = db.Column(db.BigInteger)
    reporter_type = db.Column(db.SmallInteger)
    assignee_id = db.Column(db.BigInteger)
    ticket_status = db.Column(db.SmallInteger, nullable=False, default=0)
    due_date = db.Column(db.Date)
    resolved_at = db.Column(db.DateTime(3))
    resolution = db.Column(db.String(512))
    satisfaction = db.Column(db.SmallInteger)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
    updated_at = db.Column(db.DateTime(3), server_default=func.now(3), onupdate=func.now(3))

class CmmStatsSnapshot(db.Model):
    __tablename__ = 'cmm_stats_snapshot'
    snapshot_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    stat_date = db.Column(db.Date, nullable=False)
    region_id = db.Column(db.BigInteger, nullable=False)
    total_elders = db.Column(db.Integer, default=0)
    active_elders = db.Column(db.Integer, default=0)
    new_elders = db.Column(db.Integer, default=0)
    total_alerts = db.Column(db.Integer, default=0)
    p0_alerts = db.Column(db.Integer, default=0)
    false_alerts = db.Column(db.Integer, default=0)
    avg_response_sec = db.Column(db.Integer, default=0)
    total_orders = db.Column(db.Integer, default=0)
    completed_orders = db.Column(db.Integer, default=0)
    total_workers = db.Column(db.Integer, default=0)
    active_workers = db.Column(db.Integer, default=0)
    med_reminders = db.Column(db.Integer, default=0)
    med_compliance_rate = db.Column(db.Numeric(5, 2), default=0)
    health_data_count = db.Column(db.Integer, default=0)
    ai_chat_count = db.Column(db.Integer, default=0)
    video_visit_count = db.Column(db.Integer, default=0)
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))

class CmmAuditLog(db.Model):
    __tablename__ = 'cmm_audit_log'
    log_id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    operator_id = db.Column(db.BigInteger)
    operator_name = db.Column(db.String(32))
    operator_type = db.Column(db.SmallInteger)
    module = db.Column(db.String(32), nullable=False)
    action = db.Column(db.String(32), nullable=False)
    target_type = db.Column(db.String(32))
    target_id = db.Column(db.BigInteger)
    detail = db.Column(db.Text)
    ip_address = db.Column(db.String(45))
    user_agent = db.Column(db.String(512))
    created_at = db.Column(db.DateTime(3), server_default=func.now(3))
